### ISSUE TITLE
Rollback Tutorial (Copy method no forced code upload)

### ISSUE THREAD

**Issue by danielnehrig** [rustyscreeps/screeps-starter-rust#65]
# Problem Description

I've pretty much tried everything to get the latest commit to work to no avail...
First the awful setup of https://github.com/ScreepsMods/screepsmod-auth
Then internal creeps errors with the exported `@screeps/common` env module
Eventually I got `screepsmod-auth` to work and was able to `setPassword(...)`

What I did to get it to work:

_Everything in `server` path of the screep install dir_

- `npm install screepsmod-auth` (this alone is not good enough you'll get @screeps/common errors)
- `npm install @screeps/common`
- Start the Server

But if you run now this `starter` project and deploy you'll get a internal `@screeps\backend` error telling you setex is not a function.

```
TypeError: env.setex is not a function
at Object.exports.genToken (D:\Games\steamapps\steamapps\common\Screeps\server\node_modules\@screeps\backend\lib\authlib.js:9:16)
at app.get (D:\Games\steamapps\steamapps\common\Screeps\server\node_modules\screepsmod-auth\lib\steam\index.js:49:13)
```

# How to get this shit to work without rollup code upload

- `git clone https://github.com/rustyscreeps/screeps-starter-rust`
- `git checkout c610edfb0749b9e3018448c79da09deb5633c1f6` (this brings you back to 0.21 prior move to the forced code upload logic that hard depends on authentication)
- `cargo install cargo-screeps` (https://github.com/rustyscreeps/cargo-screeps) this is so much superior I don't understand why they moved away from it.
- cd into cloned repo
- create file `screeps.toml` and copy paste below and replace `USERNAME` with your USERNAME and adjust the path to your desired folder this uses the file copy to local drive instead of server upload
```toml
[copy]
destination = "c:/Users/USERNAME/AppData/Local/Screeps/scripts/127_0_0_1___21025"
# The following are the default values for the optional copy options, uncomment to change
branch = "default"
include_files = ["pkg", "javascript"]
prune = false
```
- cargo screeps deploy -m copy

Enjoy
